@echo Building GLFW Application...
g++ -c -I. -Iinclude src/main.cpp src/glad.c src/shaderClass.cpp src/computeClass.cpp src/VAO.cpp src/VBO.cpp src/EBO.cpp src/SSBO.cpp src/texture.cpp
@echo Compilation complete, proceeding to linking...
g++ -o app.exe main.o glad.o shaderClass.o computeClass.o texture.o VAO.o VBO.o EBO.o SSBO.o -L. -lglfw3 -lopengl32 -lgdi32 -lm
@echo Linking complete, running application...
.\app